### ISSUE TITLE
doesn't load on iOS 15.6

### ISSUE THREAD

**Issue by KelseyHigham** [gregdan3/ilo-muni#13] opened 2024-08-11 14:58 UTC
i'm not really sure what to try. i've turned off content blockers. i can download the db. iOS 15.6 is from July 2022, so maybe ilo Muni uses web features that were released in the last 2 years...?

![BC07AB55-991F-4162-8B0F-9C32336781E1](https://github.com/user-attachments/assets/02f81457-6178-477b-95d9-3eb58b8bd970)

**Comment by gregdan3** [comment] 2024-08-12 03:19
> Could also be that sql.js-httpvfs uses shared workers
I don't believe this is the case? I'd have to dig through that library to know for sure, but I'm pretty sure it uses exactly one worker due to the caching situation. [This separate library](https://github.com/mmomtchev/sqlite-wasm-http) exists which uses multiple workers, although I couldn't get it working at the time because I'd have to alter it to let you pass in the WASM dependency like you for sql.js-httpvfs

Uh, I'm not sure what the issue is, or how I could know what feature is missing! I could at least throw in a check for wasm and web workers, or may try/except the chart queries

The other place there could be an issue would be ChartJS, although that would be surprising.

@KelseyHigham can you test the following few sites and see if they work on Safari 15.6?

<https://sqlite-wasm-http.momtchev.com/>: Just hit the "go" button
<https://jordemort.dev/blog/client-side-search/>: Hit "search" on the navbar, type "test" (any term works but this one has two results)
<https://www.chartjs.org/samples/2.6.0/charts/line/basic.html>: Should populate a chart right away
<https://cube-chartjs-demo.netlify.app/>: Should populate a chart in a few seconds

**Comment by KelseyHigham** [comment] 2024-08-12 17:01
![8F1F5CD7-D4CB-4E03-BCFA-6E94FCB50453](https://github.com/user-attachments/assets/0cb7239f-3b78-4704-ad0c-2491e77e0bd2)
![B03BC51E-EAB3-4DC7-9459-70A5E2FBE967](https://github.com/user-attachments/assets/c5b393ed-9523-4c46-b9a0-edbb5c2a328d)
![062E3ECE-5355-466F-8F5C-B10435FFD645](https://github.com/user-attachments/assets/94bc4824-7e93-4c31-890a-cdacd82cd05c)
![2B319883-4C33-4352-A488-815E18AAC994](https://github.com/user-attachments/assets/a22fa196-565c-4d71-b3b9-e7f6b7a444a1)
![98A2BC5E-E904-49AF-B27B-904337612E06](https://github.com/user-attachments/assets/d6933712-6822-4fa7-bcfb-b1364f4ba06d)

**Comment by KelseyHigham** [comment] 2024-08-12 17:03
it's also possible that Muni is just executing slowly on WebKit and i haven't let it run for long enough
what's an example query that should run very fast? i've clicked on a few that seem like they should run fast, but i'm not a good judge of these things

**Comment by gregdan3** [comment] 2024-08-12 17:10
https://gregdan3.github.io/ilo-muni/?query=test&minSentLen=6&scale=rel&start=1690848000&end=1722470400&smoothing=0

![image](https://github.com/user-attachments/assets/00d04106-f174-4b36-bbc3-4e310bb37456)


@KelseyHigham This query took me 1.69s to get a graph from a cold start, and it's probably as fast as you could get data from a cold start since the scope of the query is as small as possible.

![image](https://github.com/user-attachments/assets/6bab0504-4e34-412f-b444-2db16cf73f86)

**Comment by KelseyHigham** [comment] 2024-08-12 19:27
it's possible to connect an iPhone to a Mac and look at the inspector on the Mac, and i can do that today and tomorrow (and maybe wednesday morning before my flight away from where my Mac is)

the following error occurs on load. i don't see anything in the console when i type "test" and press enter:
<img width="816" alt="image" src="https://github.com/user-attachments/assets/800774f3-a7e3-4299-acdb-43e6f385b2c4">
<img width="942" alt="image" src="https://github.com/user-attachments/assets/ba6af9cd-d7ef-42fd-b319-0c1b677004ef">

**Comment by gregdan3** [comment] 2024-08-12 21:23
Turns out the issue is [probably this one](https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group): Safari did not support regex lookbehind in v15.6 (jaw dropped when i saw this, wtf???), and I use a combo lookbehind and lookahead [here](https://github.com/gregdan3/ilo-muni/blob/3611db03cb60cc266a026078657d0b7318c345f4/src/utils/constants.ts#L12) in order to split around all the delimiters of a phrase without losing the specific delimiters. Uh, oops, but that's easily fixed!

**Comment by gregdan3** [comment] 2024-08-12 23:35
may have fixed in latest @KelseyHigham; try now?

**Comment by gregdan3** [comment] 2024-08-12 23:40
![image](https://github.com/user-attachments/assets/65cea75f-2002-4163-bace-753ef4ecd525)
sent by keli a bit ago! :tada:

**Closed by gregdan3** 2024-08-12 23:40 UTC
